import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Link href="/">Home</Link>
        <Link href="/books">Show Collection</Link>
        <Link href="/books/addnew">Add New</Link>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to MADD Library.
        </h1>

        
      </main>

      <footer className={styles.footer}>
        <p> footer content goes here!</p>
      </footer>
    </div>
  )
}
